name: Folder Contributions Report

on:
  workflow_dispatch:

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo (Full History)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full commit history

      - name: Count Lines Added by Contributor in Folder
        run: |
          FOLDER="src" # Change this to your folder
          echo "Analyzing folder: $FOLDER"

          # Get contributors (name + email for accuracy)
          git log --format='%aN <%aE>' -- $FOLDER | sort | uniq > contributors.txt

          # Count total additions
          TOTAL=$(git log --pretty=tformat: --numstat -- $FOLDER | awk '{added+=$1} END {print added}')

          echo "Total additions in $FOLDER: $TOTAL"
          echo "Lines added by contributor in $FOLDER:" > report.txt
          echo "" >> report.txt

          while read contributor; do
              count=$(git log --author="$contributor" --pretty=tformat: --numstat -- $FOLDER | awk '{added+=$1} END {print added}')
              percent=$(awk "BEGIN {printf \"%.2f\", ($count/$TOTAL)*100}")
              echo "$contributor: $count lines added ($percent%)" | tee -a report.txt
          done < contributors.txt

          echo ""
          echo "Full report saved in report.txt"

      - name: Upload Contribution Report
        uses: actions/upload-artifact@v4
        with:
          name: folder-contribution-report
          path: report.txt
